---
title: "Projection municipale — `r if(!is.null(params$timestamp)) format(params$timestamp, '%d/%m/%Y %H:%M:%S') else ''`"
subtitle: "Dernière mise à jour : `r format(params$timestamp, '%d/%m %H:%M:%S')`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cosmo
params:
  timestamp: NULL
  live_data: NULL
  listes: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r global, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(DT)
library(gt)
library(scales)

live_data <- params$live_data
meta_all  <- params$meta_all
listes    <- params$listes

stopifnot(is.data.frame(live_data$live_long))
stopifnot(all(c("bureau_id", "liste", "voix") %in% names(live_data$live_long)))

out_k5 <- 
  archfile_5 |> 
  run_and_get_model_selon_k(live_data = live_data)

out_k9 <- 
  archfile_9 |> 
  run_and_get_model_selon_k(live_data = live_data)

```

# Comparaison

## Row

### Bureaux observés

```{r, echo=FALSE}
valueBox(
  value = out_k5[["nb bureaux observés"]],
  caption = "Bureaux observés",
  icon = "fa-check"
)
```

## Row

### Scores comparés

```{r}
comp_scores <- 
  list("k_5"=out_k5,
       "k_9"=out_k9) |> 
  map(.f = ~.[["scores par liste"]]) |> 
  bind_rows(.id = "k")

comp_scores |>
  select(-voix) |> 
  pivot_wider(names_from = k, values_from = score, names_prefix = "score_") |> 
  gt()
```

### Résultats comparés

```{r}
comp_res <- 
  list("k_5"=out_k5,
       "k_9"=out_k9) |> 
  map(.f = ~.[["résultats"]]) |> 
  bind_rows(.id = "k")

comp_res |> 
  pivot_wider(names_from = k, values_from = voix, names_prefix = "voix_") |> 
  gt()
```


# k = 5

## Row

### Bureaux observés

```{r, echo=FALSE}
valueBox(
  value = out_k5[["nb bureaux observés"]],
  caption = "Bureaux observés",
  icon = "fa-check"
)
```

## Row
### Scores par liste

```{r}
out_k5[["scores par liste"]] |>
  DT::datatable()
```


### Résultats projetés

```{r}
out_k5[["résultats"]] |>
  DT::datatable()
```

## Row
### Projection par bureau

```{r}
datatable(
  out_k5[["projection par bureau"]],
  options = list(
    pageLength = 10,
    scrollX = TRUE
  )
)
```

# k = 9

## Row

### Bureaux observés

```{r}
valueBox(
  value = out_k9[["nb bureaux observés"]],
  caption = "Bureaux observés",
  icon = "fa-check"
)
```

## Row
### Scores par liste

```{r}
out_k9[["scores par liste"]] |>
  DT::datatable()
```


### Résultats projetés

```{r}
out_k9[["résultats"]] |>
  DT::datatable()
```

## Row
### Projection par bureau

```{r}
datatable(
  out_k9[["projection par bureau"]],
  options = list(
    pageLength = 10,
    scrollX = TRUE
  )
)
```
